"""add class_code and course_name to timetable_entries

Revision ID: 0973ddd156c0
Revises: 2dddff6dd067
Create Date: 2026-01-29 21:34:03.932688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0973ddd156c0'
down_revision: Union[str, Sequence[str], None] = '2dddff6dd067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_entries', 'course_name',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.create_index(op.f('ix_timetable_entries_room_name'), 'timetable_entries', ['room_name'], unique=False)
    op.create_index(op.f('ix_timetable_entries_teacher_name'), 'timetable_entries', ['teacher_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_teacher_name'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_room_name'), table_name='timetable_entries')
    op.alter_column('timetable_entries', 'course_name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
