"""create calendar + timetable + class_sessions

Revision ID: eb3384e83892
Revises: 9dddfaf41201
Create Date: 2026-01-21 22:22:22.180653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3384e83892'
down_revision: Union[str, Sequence[str], None] = '9dddfaf41201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('is_school_day', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_days_day'), 'calendar_days', ['day'], unique=True)
    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=True),
    sa.Column('teacher_username', sa.String(length=50), nullable=True),
    sa.Column('teacher_name', sa.String(length=120), nullable=True),
    sa.Column('room_code', sa.String(length=50), nullable=True),
    sa.Column('room_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origin_session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sessions_day'), 'class_sessions', ['day'], unique=False)
    op.create_index(op.f('ix_class_sessions_group_code'), 'class_sessions', ['group_code'], unique=False)
    op.create_index(op.f('ix_class_sessions_slot'), 'class_sessions', ['slot'], unique=False)
    op.create_index(op.f('ix_class_sessions_status'), 'class_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_class_sessions_subject_code'), 'class_sessions', ['subject_code'], unique=False)
    op.create_index(op.f('ix_class_sessions_teacher_username'), 'class_sessions', ['teacher_username'], unique=False)
    op.create_index(op.f('ix_class_sessions_weekday'), 'class_sessions', ['weekday'], unique=False)
    op.create_table('timetable_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_versions_code'), 'timetable_versions', ['code'], unique=False)
    op.create_index(op.f('ix_timetable_versions_end_date'), 'timetable_versions', ['end_date'], unique=False)
    op.create_index(op.f('ix_timetable_versions_start_date'), 'timetable_versions', ['start_date'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_version_id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=True),
    sa.Column('teacher_username', sa.String(length=50), nullable=True),
    sa.Column('teacher_name', sa.String(length=120), nullable=True),
    sa.Column('room_code', sa.String(length=50), nullable=True),
    sa.Column('room_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['timetable_version_id'], ['timetable_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_group_code'), 'timetable_entries', ['group_code'], unique=False)
    op.create_index(op.f('ix_timetable_entries_slot'), 'timetable_entries', ['slot'], unique=False)
    op.create_index(op.f('ix_timetable_entries_subject_code'), 'timetable_entries', ['subject_code'], unique=False)
    op.create_index(op.f('ix_timetable_entries_teacher_username'), 'timetable_entries', ['teacher_username'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_version_id'), 'timetable_entries', ['timetable_version_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_weekday'), 'timetable_entries', ['weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_weekday'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_timetable_version_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_teacher_username'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_subject_code'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_slot'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_group_code'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_timetable_versions_start_date'), table_name='timetable_versions')
    op.drop_index(op.f('ix_timetable_versions_end_date'), table_name='timetable_versions')
    op.drop_index(op.f('ix_timetable_versions_code'), table_name='timetable_versions')
    op.drop_table('timetable_versions')
    op.drop_index(op.f('ix_class_sessions_weekday'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_teacher_username'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_subject_code'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_status'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_slot'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_group_code'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_day'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_calendar_days_day'), table_name='calendar_days')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###
